// GENERATED custom-solver codegen (ADC-462, Spec 3 section 20 / criterion 23 / 24.9): the
// @pops.lib.solver IR-DSL lowers a CUSTOM Richardson solver to a self-contained C++ kernel
// (pops.lib.generate_solver_cpp), emitted by scripts/gen_solver_kernel.py into the header included
// below. This test COMPILES that generated kernel against the real pops::pops runtime and RUNS it on a
// known linear system, proving the lowering is not merely emitted but executes -- and matches the
// native pops::richardson_solve (the same matrix-free Krylov backend the DSL maps onto).
//
// OPERATOR: the SAME SPD Helmholtz operator A = I - alpha*Lap (alpha = 0.1) as test_generic_krylov,
//   supplied as a value-typed functor. The generated kernel takes the operator as a TEMPLATE
//   parameter (no std::function indirection in the loop), so the SAME functor drives both the
//   generated solver and the native richardson_solve (which wraps it in an pops::ApplyFn).
//
// MANUFACTURED SOLUTION phi_exact (a sum of periodic sine modes); rhs = A(phi_exact) (discretization
//   -exact, so the test exercises the SOLVER not the scheme). We require:
//     - the generated solver converges and recovers phi_exact (max|x - exact| < 1e-6), AND
//     - it matches the native richardson_solve cell-by-cell (same omega / tol / operator) to a tight
//       tolerance -- the generated loop IS the native Richardson iteration, lowered from the IR.
//
// SERIAL test: single box, DistributionMapping(1, 1); the dot products are nonetheless COLLECTIVE
// (pops::dot -> all_reduce_sum, the identity in serial).

#include "pops_generated_solver.hpp"  // GENERATED by scripts/gen_solver_kernel.py: richardson_gen_solve

#include <pops/numerics/elliptic/linear/generic_krylov.hpp>  // pops::richardson_solve (reference)
#include <pops/numerics/elliptic/poisson/poisson_operator.hpp>  // apply_laplacian (shared 5-point matvec)
#include <pops/mesh/layout/box_array.hpp>
#include <pops/mesh/layout/distribution_mapping.hpp>
#include <pops/mesh/execution/for_each.hpp>
#include <pops/mesh/geometry/geometry.hpp>
#include <pops/mesh/storage/mf_arith.hpp>
#include <pops/mesh/storage/multifab.hpp>
#include <pops/mesh/boundary/physical_bc.hpp>  // fill_ghosts (periodic ghost exchange)

#include "test_harness.hpp"  // pops::test::Checker + kPi

#include <cmath>
#include <cstdio>
#include <vector>

using namespace pops;
using pops::test::kPi;

namespace {

constexpr int kN = 32;        // 32 x 32 periodic grid (same as test_generic_krylov)
constexpr Real kAlpha = 0.1;  // Helmholtz coefficient: A = I - alpha*Lap (SPD, well-conditioned)
// omega / tol MUST match scripts/gen_solver_kernel.py (GEN_OMEGA / GEN_ABS_TOL) so the generated and
// native Richardson loops trace the same iterates and stop at the same residual (parity below).
constexpr Real kOmega =
    2.0e-3;  // under-relaxes the SPD operator (lambda_max ~ 820: stable < 2.4e-3)
constexpr Real kAbsTol = 1.0e-8;  // ABSOLUTE residual L2 norm the generated loop breaks on

struct HelmholtzCombineKernel {
  Array4 outv;
  ConstArray4 inv, lapv;
  Real alpha;
  POPS_HD void operator()(int i, int j) const { outv(i, j) = inv(i, j) - alpha * lapv(i, j); }
};

// The matrix-free SPD Helmholtz operator as a VALUE-TYPED functor: A(out, in) = in - alpha*Lap(in).
// The generated kernel takes it as a template parameter (inlined; no std::function in the loop); the
// native richardson_solve wraps the same object in an pops::ApplyFn. The lap scratch is captured once.
struct HelmholtzOp {
  Geometry geom;
  BCRec bc;
  MultiFab* lap_tmp;
  void operator()(MultiFab& out, const MultiFab& in) const {
    MultiFab& in_mut = const_cast<MultiFab&>(in);  // only the ghosts are written (solver contract)
    fill_ghosts(in_mut, geom.domain, bc);
    apply_laplacian(in_mut, geom, *lap_tmp);
    for (int li = 0; li < out.local_size(); ++li) {
      Array4 ov = out.fab(li).array();
      const ConstArray4 iv = in.fab(li).const_array();
      const ConstArray4 lv = lap_tmp->fab(li).const_array();
      for_each_cell(out.box(li), HelmholtzCombineKernel{ov, iv, lv, kAlpha});
    }
  }
};

POPS_HD Real phi_exact(Real x, Real y) {
  return std::sin(2 * kPi * x) * std::sin(2 * kPi * y) +
         Real(0.5) * std::sin(4 * kPi * x) * std::sin(2 * kPi * y) +
         Real(0.3) * std::cos(2 * kPi * x) * std::cos(6 * kPi * y);
}

struct SampleExactKernel {
  Array4 af;
  Geometry geom;
  POPS_HD void operator()(int i, int j) const {
    af(i, j) = phi_exact(geom.x_cell(i), geom.y_cell(j));
  }
};

Real max_abs_diff(const MultiFab& a, const MultiFab& b) {
  Real d = 0;
  for (int li = 0; li < a.local_size(); ++li) {
    const ConstArray4 pa = a.fab(li).const_array();
    const ConstArray4 pb = b.fab(li).const_array();
    const Box2D bx = a.box(li);
    for (int j = bx.lo[1]; j <= bx.hi[1]; ++j)
      for (int i = bx.lo[0]; i <= bx.hi[0]; ++i)
        d = std::fmax(d, std::fabs(pa(i, j) - pb(i, j)));
  }
  return static_cast<Real>(all_reduce_max(static_cast<double>(d)));
}

}  // namespace

int main() {
  pops::test::Checker chk(pops::test::Checker::Style::Terse);

  Box2D dom = Box2D::from_extents(kN, kN);
  Geometry geom{dom, 0.0, 1.0, 0.0, 1.0};
  BoxArray ba(std::vector<Box2D>{dom});
  DistributionMapping dm(1, 1);
  BCRec bc;  // all faces Periodic

  MultiFab lap_tmp(ba, dm, 1, 0);
  HelmholtzOp op{geom, bc, &lap_tmp};

  // Manufactured solution + the discretization-exact rhs = A(phi_exact).
  MultiFab phi_exact_mf(ba, dm, 1, 1);
  for (int li = 0; li < phi_exact_mf.local_size(); ++li) {
    Array4 af = phi_exact_mf.fab(li).array();
    for_each_cell(phi_exact_mf.box(li), SampleExactKernel{af, geom});
  }
  MultiFab rhs(ba, dm, 1, 0);
  op(rhs, phi_exact_mf);

  // --- Run the GENERATED custom solver (the lowered @pops.lib.solver IR) ---
  MultiFab x_gen(ba, dm, 1, 1);
  x_gen.set_val(0.0);
  const KrylovResult r_gen = richardson_gen_solve(op, x_gen, rhs);
  const Real err_gen = max_abs_diff(x_gen, phi_exact_mf);
  std::printf("generated : %s in %d iters (rel=%.2e) | max|x - exact| = %.3e\n",
              r_gen.converged ? "CONVERGED" : "FAILED", r_gen.iters, r_gen.rel_residual, err_gen);
  chk(r_gen.converged, "generated_converged");
  chk(r_gen.iters > 1, "generated_iters_gt_1");
  chk(err_gen < 1e-5, "generated_recovers_exact");

  // --- Run the NATIVE richardson_solve with the SAME operator / omega (the reference) ---
  // The native loop stops on a RELATIVE tolerance (||r|| <= rel_tol * ||b||); the generated loop on
  // an ABSOLUTE one (||r|| <= kAbsTol). Feed the native the matching relative tol kAbsTol / ||b|| so
  // both stop at the same residual level and trace the same iterates from x = 0.
  MultiFab x_ref(ba, dm, 1, 1);
  x_ref.set_val(0.0);
  ApplyFn A = [&](MultiFab& out, const MultiFab& in) { op(out, in); };
  const Real bnorm = std::sqrt(pops::dot(rhs, rhs));
  const Real rel_tol = kAbsTol / bnorm;
  const KrylovResult r_ref = richardson_solve(A, x_ref, rhs, kOmega, rel_tol, 1000000);
  const Real err_ref = max_abs_diff(x_ref, phi_exact_mf);
  std::printf("native    : %s in %d iters (rel=%.2e) | max|x - exact| = %.3e\n",
              r_ref.converged ? "CONVERGED" : "FAILED", r_ref.iters, r_ref.rel_residual, err_ref);
  chk(r_ref.converged, "native_converged");

  // --- PARITY: the generated kernel IS the native Richardson iteration (same omega / tol / op). ---
  // Both start from x = 0 with identical omega and the same discrete operator, so they trace the same
  // sequence of iterates to the same fixed point; the recovered solutions must agree tightly.
  const Real parity = max_abs_diff(x_gen, x_ref);
  std::printf("parity    : max|x_gen - x_native| = %.3e\n", parity);
  chk(parity < 1e-6, "generated_matches_native_richardson");

  if (chk.fails() == 0)
    std::printf("OK test_solver_codegen_generated\n");
  return chk.failed();
}
