#pragma once

#include <adc/runtime/export.hpp>  // ADC_EXPORT (default visibility across the hidden _adc module)

#include <string>

/// @file
/// @brief ABI key of the adc core: stable string identifying the (compiler, C++ standard, header
///        tree signature) combination a unit was compiled with.
///
/// MOTIVATION ("production" DSL path). A .so loader generated by the DSL (cf.
/// dsl.emit_cpp_native_loader) inlines the adc::add_compiled_model header template and calls
/// out-of-line methods of adc::System DEFINED in the already-loaded _adc module. The loader and the
/// module MUST share the same ABI (same headers, same compiler, same standard); otherwise the
/// memory layout of objects crossing the boundary (System, GridContext, BlockClosures...)
/// diverges -> SILENT undefined behavior. We make the incompatibility EXPLICIT: the loader exposes
/// adc_native_abi_key() (key frozen at ITS compilation) and the System compares it against ITS own
/// abi_key() at load time (add_native_block); a mismatch raises a clear error instead of UB.
///
/// Key construction (parallel to adc_cases/common/native.py::_abi_key):
///   - __VERSION__: compiler identity + version (g++/clang++/Apple clang...);
///   - __cplusplus: effective C++ standard (thus -std= and the compiler mode);
///   - ADC_HEADER_SIG: signature of the core header tree, INJECTED by the build (CMake on the
///                     module side, -D flag on the loader side); its value changes if a header
///                     changes, so the key changes and the incompatibility is detected. Absent (old
///                     build / manual build) -> literal token "unknown": the key stays stable and
///                     comparable, it then captures only compiler + standard (graceful degradation,
///                     never silent UB since both sides see the same "unknown" if built the same).
///   - kokkos=0|1: ADC_HAS_KOKKOS of the unit. This macro CHANGES the layout of types crossing
///                     the boundary (allocator.hpp: Fab backing malloc vs Kokkos::SharedSpace pool;
///                     types.hpp: ADC_HD): a serial loader on a Kokkos module (or the reverse) was
///                     previously ACCEPTED by the key -> mute serial fallback in one direction, UB
///                     in the other. The divergence is now rejected explicitly; parity is restored
///                     via ADC_KOKKOS_ROOT (cf. dsl._native_kokkos_flags) or a serial module.
///   - stdlib=...: C++ standard library linked (libc++ _LIBCPP_VERSION / libstdc++ __GLIBCXX__).
///                     Two toolchains may share __VERSION__ AND __cplusplus but link stdlibs with
///                     INCOMPATIBLE ABIs (std::string/std::function cross the loader boundary).
///                     Detects the clang -stdlib=libc++ vs libstdc++ mix (conda/system mix). The
///                     macros are visible here because <string> is included.

#ifndef ADC_HEADER_SIG
#define ADC_HEADER_SIG "unknown"
#endif

// Indirection to stringify the value of a macro (not its name). Defined BEFORE the tokens that use
// it (expansion happens at use, but keeping it readable does no harm).
#define ADC_ABI_STR_(x) #x
#define ADC_ABI_STR(x) ADC_ABI_STR_(x)

// Kokkos token: evaluated PER UNIT (_adc module on one side, generated .so loader on the other).
#ifdef ADC_HAS_KOKKOS
#define ADC_ABI_KOKKOS "1"
#else
#define ADC_ABI_KOKKOS "0"
#endif

// stdlib token: identity + version of the linked standard library. _LIBCPP_VERSION /
// __GLIBCXX__ are only defined after including a stdlib header (<string> above).
#if defined(_LIBCPP_VERSION)
#define ADC_ABI_STDLIB "libc++_" ADC_ABI_STR(_LIBCPP_VERSION)
#elif defined(__GLIBCXX__)
#define ADC_ABI_STDLIB "libstdc++_" ADC_ABI_STR(__GLIBCXX__)
#else
#define ADC_ABI_STDLIB "unknown"
#endif

// Compiler token: __VERSION__ (GCC/Clang/AppleClang) is already a string LITERAL; MSVC does NOT
// define it -> stringify _MSC_FULL_VER. Keeps the key comparable cross-compiler (native Windows
// port, ADC-99/100). POSIX unchanged (ADC_ABI_COMPILER == __VERSION__).
#if defined(__VERSION__)
#define ADC_ABI_COMPILER __VERSION__
#elif defined(_MSC_FULL_VER)
#define ADC_ABI_COMPILER "MSVC_" ADC_ABI_STR(_MSC_FULL_VER)
#else
#define ADC_ABI_COMPILER "unknown"
#endif

// ABI key of the current TRANSLATION UNIT, as a pure literal concatenated by the preprocessor:
// "compiler=<__VERSION__>;std=<__cplusplus>;headers=<ADC_HEADER_SIG>;kokkos=<0|1>;stdlib=<...>".
// All tokens are string literals (__VERSION__ and ADC_HEADER_SIG already are), so the key is frozen
// in the .rodata of EACH TU at preprocessing -- NO function call.
//
// WHY a literal and not an inline function (real CI bug, ELF/Linux): a .so loader is loaded
// RTLD_GLOBAL and an `inline` function (weak linkage, default visibility) that would build the key
// would be INTERPOSED by the dynamic linker onto the copy in the already-loaded module -- the
// loader would then return the key OF THE MODULE and the guard would compare the module key against
// itself (tautology: ABI never rejected). Whether interposition happened depended on the compiler's
// inlining threshold (the short function was inlined -> correct local key; lengthened by
// kokkos=/stdlib=, gcc -O2 stopped inlining it -> interposition -> guard neutralized, caught by
// test_amr_native_loader). A literal crosses no symbol: no interposition.
// NB: the parsers (dsl._adc_cxx_std_from_module / module_header_signature) scan by token prefix
// ("std=", "headers=") -> insensitive to ADDING tokens at the tail.
#define ADC_ABI_KEY_LITERAL                                                          \
  "compiler=" ADC_ABI_COMPILER ";std=" ADC_ABI_STR(__cplusplus) ";headers=" ADC_HEADER_SIG \
  ";kokkos=" ADC_ABI_KOKKOS ";stdlib=" ADC_ABI_STDLIB

namespace adc {
namespace detail {

/// ABI key of the current TU (cf. ADC_ABI_KEY_LITERAL). Kept for the MODULE side
/// (out-of-line abi_key() in system.cpp); a generated LOADER must return ADC_ABI_KEY_LITERAL
/// directly (literal local to its TU, insensitive to ELF interposition -- cf. above).
inline std::string abi_key_string() { return ADC_ABI_KEY_LITERAL; }

}  // namespace detail

/// ABI key of the module (TU system.cpp). ADC_EXPORT: exported so that add_native_block can read
/// the key of the already-loaded module and compare it to the one baked into the .so loader. Defined
/// out-of-line (system.cpp) to freeze the key at the compilation OF THE MODULE.
ADC_EXPORT std::string abi_key();

}  // namespace adc
