#pragma once

#include <adc/runtime/block_builder.hpp>

#include <adc/mesh/box_array.hpp>
#include <adc/mesh/distribution_mapping.hpp>
#include <adc/mesh/fill_boundary.hpp>
#include <adc/mesh/for_each.hpp>  // device_fence: barrier before host read (unified memory)
#include <adc/mesh/geometry.hpp>
#include <adc/mesh/multifab.hpp>
#include <adc/mesh/physical_bc.hpp>

#include <adc/core/physical_model.hpp>  // aux_comps<Model>: aux channel width of the generated model
#include <adc/runtime/runtime_params.hpp>  // RuntimeParams: RUNTIME params (P7-b) carried by the ABI

#include <string>
#include <type_traits>
#include <utility>

/// @file
/// @brief C ABI of an AOT-COMPILED block: a model generated by the DSL, compiled ahead-of-time into a
///        .so, exposes its residual / advance / wave speed / Poisson right-hand side through extern "C"
///        functions. The .so RUNS the PRODUCTION path (block_builder.hpp: assemble_rhs<Limiter, Flux>,
///        core SSPRK2/IMEX) on the CompositeModel<Gen...> known AT ITS compilation: the numerics are
///        inlined, identical to a native add_block block. Only the mesh transits through flat arrays
///        (marshaling on the System side, like add_dynamic_block): no C++ symbol dependency across the
///        dlopen (clean ABI). The zero-copy / GPU version (model compiled into the Kokkos build, without
///        marshaling) is a separate path.
///
/// Array layout: component-major c*n*n + j*n + i (like System::copy_state). A generated .so reduces to:
/// include the brick + this header, write
///   namespace adc_generated { using Model = adc::CompositeModel<...>; }
/// then ADC_DEFINE_COMPILED_BLOCK(adc_generated::Model).

namespace adc::compiled_block {

/// Local single-grid mesh rebuilt inside the .so + aux filled from the System array.
struct LocalGrid {
  Box2D dom;
  Geometry geom;
  BoxArray ba;
  DistributionMapping dm;
  BCRec bc;
  bool periodic;
  MultiFab aux;  // naux comp (phi, grad phi, [B_z, T_e...]), 1 ghost
};

/// @p naux = width of the aux channel the model READS (aux_comps<Model>(), >= 3). The flat array
/// @p aux_in carries EXACTLY @p naux components (marshaled by the System via copy_state); we copy them
/// all into the internal aux so that assemble_rhs (load_aux<aux_comps<Model>()>) reads B_z/T_e.
/// The ghosts (B_z/T_e included) are filled by the same BCs as the System.
inline LocalGrid make_grid(int n, double dx, double dy, bool periodic, const double* aux_in,
                           int naux) {
  Box2D dom = Box2D::from_extents(n, n);
  Geometry geom{dom, 0.0, dx * n, 0.0, dy * n};
  BoxArray ba = BoxArray::from_domain(dom, n);
  DistributionMapping dm(ba.size(), 1);  // single-rank .so (prototype CPU block)
  BCRec bc;
  if (!periodic) bc.xlo = bc.xhi = bc.ylo = bc.yhi = BCType::Foextrap;
  MultiFab aux(ba, dm, naux, 1);
  aux.set_val(0.0);
  if (aux_in) {  // aux interior from the array, then ghosts (same BCs as the System)
    Array4 a = aux.fab(0).array();
    const std::size_t nn = static_cast<std::size_t>(n) * n;
    for (int c = 0; c < naux; ++c)
      for (int j = 0; j < n; ++j)
        for (int i = 0; i < n; ++i)
          a(i, j, c) = aux_in[static_cast<std::size_t>(c) * nn + static_cast<std::size_t>(j) * n + i];
    if (periodic)
      fill_boundary(aux, dom, Periodicity{true, true});
    else
      fill_ghosts(aux, dom, bc);
  }
  return LocalGrid{dom, geom, ba, dm, bc, periodic, std::move(aux)};
}

/// Copies @p nv components of the component-major flat array @p in into the INTERIOR of fab(0) (without
/// touching the ghosts). Marshaling input side: layout c*n*n + j*n + i (cf. System::copy_state).
inline void fill_interior(MultiFab& mf, const double* in, int n, int nv) {
  Array4 a = mf.fab(0).array();
  const std::size_t nn = static_cast<std::size_t>(n) * n;
  for (int c = 0; c < nv; ++c)
    for (int j = 0; j < n; ++j)
      for (int i = 0; i < n; ++i)
        a(i, j, c) = in[static_cast<std::size_t>(c) * nn + static_cast<std::size_t>(j) * n + i];
}

/// Copies the INTERIOR of fab(0) (@p nv components) into the component-major flat array @p out.
/// Output side of fill_interior. PRIOR device_fence(): the assemble_rhs / advance kernels are ASYNC, we
/// wait before reading the unified memory on the host (otherwise race -> partial result).
inline void extract(const MultiFab& mf, double* out, int n, int nv) {
  device_fence();  // assemble_rhs / advance have launched ASYNC kernels; wait before the host
                   // read of the unified memory (otherwise race -> partial result on GPU).
  const ConstArray4 a = mf.fab(0).const_array();
  const std::size_t nn = static_cast<std::size_t>(n) * n;
  for (int c = 0; c < nv; ++c)
    for (int j = 0; j < n; ++j)
      for (int i = 0; i < n; ++i)
        out[static_cast<std::size_t>(c) * nn + static_cast<std::size_t>(j) * n + i] = a(i, j, c);
}

/// Detects (SFINAE) whether a brick B exposes a `params` member of type adc::RuntimeParams (DSL bricks
/// carry one only if a formula reads a runtime parameter, P7-b). A native brick or a DSL brick WITHOUT
/// a runtime param has none -> the helpers below are then no-ops (bit-identity).
template <class B, class = void>
struct HasRuntimeParams : std::false_type {};
template <class B>
struct HasRuntimeParams<B, std::void_t<decltype(std::declval<B&>().params)>>
    : std::is_same<std::decay_t<decltype(std::declval<B&>().params)>, RuntimeParams> {};

/// Writes @p rp into the `params` member of brick @p b if it has one (P7-b); otherwise no-op. The brick
/// then behaves as if it had those parameter values in place of its declaration defaults.
template <class B>
inline void apply_runtime_params(B& b, const RuntimeParams& rp) {
  if constexpr (HasRuntimeParams<B>::value) b.params = rp;
}

/// Builds a Model (CompositeModel<Hyp, Src, Ell>) and injects the @p npar runtime parameter values
/// @p pvals into EACH brick that carries a `params` member (P7-b). @p pvals == nullptr or @p npar == 0
/// -> no injection: the Model keeps its declaration defaults (thus identical to a const param).
/// Centralizes the single point of the AOT ABI that depends on the runtime params; native bricks /
/// bricks without a runtime param are unchanged (apply_runtime_params is a no-op on them).
template <class Model>
Model make_model_with_params(const double* pvals, int npar) {
  Model model{};
  if (pvals && npar > 0) {
    RuntimeParams rp;
    rp.count = npar > kMaxRuntimeParams ? kMaxRuntimeParams : npar;
    for (int k = 0; k < rp.count; ++k) rp.values[k] = static_cast<Real>(pvals[k]);
    apply_runtime_params(model.hyp, rp);
    apply_runtime_params(model.src, rp);
    apply_runtime_params(model.ell, rp);
  }
  return model;
}

/// Number of runtime parameters the `params` member of a brick @p b carries (0 if the brick has none).
/// Used by model_nparams to report to the loader the expected size of the parameter block.
template <class B>
inline int brick_nparams(const B& b) {
  if constexpr (HasRuntimeParams<B>::value) return b.params.count;
  else { (void)b; return 0; }
}

/// `params` block (full RuntimeParams) of the model: the FIRST brick that carries one (all carry the
/// same full block when the model has runtime params). Empty RuntimeParams (count=0) if no brick has a
/// runtime param.
template <class Model>
inline RuntimeParams model_params(const Model& model) {
  if constexpr (HasRuntimeParams<std::decay_t<decltype(model.hyp)>>::value) return model.hyp.params;
  else if constexpr (HasRuntimeParams<std::decay_t<decltype(model.src)>>::value) return model.src.params;
  else if constexpr (HasRuntimeParams<std::decay_t<decltype(model.ell)>>::value) return model.ell.params;
  else { (void)model; return RuntimeParams{}; }
}

/// Number of runtime parameters declared by @p Model (P7-b): max of the `params.count` of its 3 bricks
/// (each carries the SAME full block when the model has runtime params; 0 everywhere otherwise). Exposed
/// by adc_compiled_nparams() so the loader sizes the value block it transmits.
template <class Model>
inline int model_nparams() {
  Model model{};
  int a = brick_nparams(model.hyp), b = brick_nparams(model.src), c = brick_nparams(model.ell);
  int m = a > b ? a : b;
  return m > c ? m : c;
}

/// Writes the DECLARATION values of @p Model's runtime parameters into @p out (at least
/// model_nparams<Model>() doubles). Used by the loader to SEED its value block: a later set_param
/// overwrites only one entry, the others keep their declaration default (no reset to zero).
template <class Model>
void model_param_defaults(double* out) {
  Model model{};
  const RuntimeParams rp = model_params(model);
  for (int k = 0; k < rp.count; ++k) out[k] = static_cast<double>(rp.values[k]);
}

/// Residual -div F + S of the production path (assemble_rhs<Limiter, Flux>) on the generated model.
/// GHOSTS: we allocate the local state with block_n_ghost(lim) (3 for weno5, its 5-point stencil,
/// otherwise 2 MUSCL) -- SAME mechanism as System::add_block (set_block_ghosts, PR #88). Without that
/// width, assemble_rhs would read out of bounds of the .so local grid. none/minmod/vanleer (<=2 ghosts):
/// allocation and result bit-identical to history (the surplus ghost is a no-op).
template <class Model>
void residual(const double* U, double* R, const double* aux_in, int n, double dx, double dy,
              bool periodic, const std::string& lim, const std::string& riem, bool recon_prim,
              const double* pvals = nullptr, int npar = 0, double pos_floor = 0) {
  LocalGrid lg = make_grid(n, dx, dy, periodic, aux_in, aux_comps<Model>());
  MultiFab Umf(lg.ba, lg.dm, Model::n_vars, block_n_ghost(lim)), Rmf(lg.ba, lg.dm, Model::n_vars, 0);
  fill_interior(Umf, U, n, Model::n_vars);
  const GridContext ctx{lg.dom, lg.bc, lg.geom, &lg.aux};
  Model model = make_model_with_params<Model>(pvals, npar);  // P7-b: runtime params (no-op if const)
  BlockClosures clo = make_block(model, lim, riem, ctx, /*imex=*/false, recon_prim, "ssprk2", {}, {},
                                 nullptr, static_cast<Real>(pos_floor));
  clo.rhs_into(Umf, Rmf);
  extract(Rmf, R, n, Model::n_vars);
}

/// Advances by @p nsub substeps (explicit SSPRK2, or ForwardEuler + implicit source if imex).
template <class Model>
void advance(double* U, const double* aux_in, int n, double dx, double dy, bool periodic,
             const std::string& lim, const std::string& riem, bool recon_prim, bool imex,
             double dt, int nsub, const double* pvals = nullptr, int npar = 0,
             double pos_floor = 0) {
  LocalGrid lg = make_grid(n, dx, dy, periodic, aux_in, aux_comps<Model>());
  // block_n_ghost(lim): 3 for weno5 (5-point stencil), 2 MUSCL otherwise. cf. residual above.
  MultiFab Umf(lg.ba, lg.dm, Model::n_vars, block_n_ghost(lim));
  fill_interior(Umf, U, n, Model::n_vars);
  const GridContext ctx{lg.dom, lg.bc, lg.geom, &lg.aux};
  Model model = make_model_with_params<Model>(pvals, npar);  // P7-b: runtime params (no-op if const)
  BlockClosures clo = make_block(model, lim, riem, ctx, imex, recon_prim, "ssprk2", {}, {}, nullptr,
                                 static_cast<Real>(pos_floor));
  clo.advance(Umf, dt, nsub);
  extract(Umf, U, n, Model::n_vars);
}

/// Max wave speed of the block (for the CFL step on the System side) via make_max_speed on the generated model.
template <class Model>
double max_speed(const double* U, const double* aux_in, int n, double dx, double dy, bool periodic,
                 const double* pvals = nullptr, int npar = 0) {
  LocalGrid lg = make_grid(n, dx, dy, periodic, aux_in, aux_comps<Model>());
  MultiFab Umf(lg.ba, lg.dm, Model::n_vars, 2);
  fill_interior(Umf, U, n, Model::n_vars);
  const GridContext ctx{lg.dom, lg.bc, lg.geom, &lg.aux};
  Model model = make_model_with_params<Model>(pvals, npar);  // P7-b: runtime params (no-op if const)
  return make_max_speed(model, ctx)(Umf);
}

/// PRIMITIVE -> CONSERVATIVE conversion cell by cell (M.to_conservative) on component-major flat arrays
/// ncomp*n*n. Used by System::set_primitive_state through the AOT block (init from the primitives).
/// Model without conversion (scalar) -> identity (HasPrimitiveVars false). No mesh / ghosts: POINTWISE
/// conversion, thus a simple loop over the n*n cells.
template <class Model>
void to_conservative(const double* P, double* U, int n, const double* pvals = nullptr, int npar = 0) {
  constexpr int NV = Model::n_vars;
  const std::size_t nn = static_cast<std::size_t>(n) * n;
  Model model = make_model_with_params<Model>(pvals, npar);  // P7-b: runtime params (no-op if const)
  for (std::size_t k = 0; k < nn; ++k) {
    if constexpr (HasPrimitiveVars<Model>) {
      typename Model::Prim p{};
      for (int c = 0; c < NV; ++c) p[c] = static_cast<Real>(P[static_cast<std::size_t>(c) * nn + k]);
      const typename Model::State u = model.to_conservative(p);
      for (int c = 0; c < NV; ++c) U[static_cast<std::size_t>(c) * nn + k] = static_cast<double>(u[c]);
    } else {
      for (int c = 0; c < NV; ++c) U[static_cast<std::size_t>(c) * nn + k] = P[static_cast<std::size_t>(c) * nn + k];
    }
  }
}

/// CONSERVATIVE -> PRIMITIVE conversion cell by cell (M.to_primitive). Diagnostic counterpart of
/// to_conservative (System::get_primitive_state through the AOT block). Identity if the model exposes
/// no conversion.
template <class Model>
void to_primitive(const double* U, double* P, int n, const double* pvals = nullptr, int npar = 0) {
  constexpr int NV = Model::n_vars;
  const std::size_t nn = static_cast<std::size_t>(n) * n;
  Model model = make_model_with_params<Model>(pvals, npar);  // P7-b: runtime params (no-op if const)
  for (std::size_t k = 0; k < nn; ++k) {
    if constexpr (HasPrimitiveVars<Model>) {
      typename Model::State u{};
      for (int c = 0; c < NV; ++c) u[c] = static_cast<Real>(U[static_cast<std::size_t>(c) * nn + k]);
      const typename Model::Prim p = model.to_primitive(u);
      for (int c = 0; c < NV; ++c) P[static_cast<std::size_t>(c) * nn + k] = static_cast<double>(p[c]);
    } else {
      for (int c = 0; c < NV; ++c) P[static_cast<std::size_t>(c) * nn + k] = U[static_cast<std::size_t>(c) * nn + k];
    }
  }
}

/// Elliptic right-hand side f(U) of the block (the System adds it to its Poisson sum).
template <class Model>
void poisson_rhs(const double* U, double* rhs_out, int n, const double* pvals = nullptr,
                 int npar = 0) {
  Box2D dom = Box2D::from_extents(n, n);
  BoxArray ba = BoxArray::from_domain(dom, n);
  DistributionMapping dm(ba.size(), 1);
  MultiFab Umf(ba, dm, Model::n_vars, 2), rhsmf(ba, dm, 1, 0);
  fill_interior(Umf, U, n, Model::n_vars);
  rhsmf.set_val(0.0);
  Model model = make_model_with_params<Model>(pvals, npar);  // P7-b: runtime params (no-op if const)
  make_poisson_rhs(model)(Umf, rhsmf);
  const ConstArray4 r = rhsmf.fab(0).const_array();
  const std::size_t nn = static_cast<std::size_t>(n) * n;
  (void)nn;
  for (int j = 0; j < n; ++j)
    for (int i = 0; i < n; ++i) rhs_out[static_cast<std::size_t>(j) * n + i] = r(i, j, 0);
}

}  // namespace adc::compiled_block

/// Defines the extern "C" ABI of the compiled block for the model @p MODEL (a top-level alias WITHOUT a
/// comma: write `using Model = adc::CompositeModel<...>;` then pass this alias).
///
/// P7-b (RUNTIME PARAMS). IN ADDITION to the historical symbols (unchanged, thus bit-identical for a
/// model without a runtime param), we emit `_p`-SUFFIXED variants that take a flat block of runtime
/// parameters (const double* pvals, int npar) injected into the model before execution, and
/// `adc_compiled_nparams()` (number of runtime params of the model, 0 if none). The loader
/// (native_loader.hpp) PREFERS the `_p` symbols when present; an old .so without them falls back to the
/// historical symbols (no runtime param). The historical symbols delegate to the same templates with
/// pvals=nullptr/npar=0 -> strict bit-identity of the const-params path.
#define ADC_DEFINE_COMPILED_BLOCK(MODEL)                                                            \
  extern "C" int adc_model_nvars() { return MODEL::n_vars; }                                        \
  extern "C" int adc_compiled_naux() { return adc::aux_comps<MODEL>(); }                            \
  extern "C" int adc_compiled_nparams() { return adc::compiled_block::model_nparams<MODEL>(); }     \
  extern "C" void adc_compiled_param_defaults(double* out) {                                        \
    adc::compiled_block::model_param_defaults<MODEL>(out);                                          \
  }                                                                                                 \
  extern "C" void adc_compiled_residual(const double* U, double* R, const double* aux, int n,       \
                                        double dx, double dy, int periodic, const char* lim,        \
                                        const char* riem, int recon_prim) {                         \
    adc::compiled_block::residual<MODEL>(U, R, aux, n, dx, dy, periodic != 0, lim, riem,            \
                                         recon_prim != 0);                                          \
  }                                                                                                 \
  extern "C" void adc_compiled_residual_p(const double* U, double* R, const double* aux, int n,     \
                                          double dx, double dy, int periodic, const char* lim,      \
                                          const char* riem, int recon_prim, const double* pvals,    \
                                          int npar, double pos_floor) {                             \
    adc::compiled_block::residual<MODEL>(U, R, aux, n, dx, dy, periodic != 0, lim, riem,            \
                                         recon_prim != 0, pvals, npar, pos_floor);                  \
  }                                                                                                 \
  extern "C" void adc_compiled_advance(double* U, const double* aux, int n, double dx, double dy,   \
                                       int periodic, const char* lim, const char* riem,             \
                                       int recon_prim, int imex, double dt, int nsub) {             \
    adc::compiled_block::advance<MODEL>(U, aux, n, dx, dy, periodic != 0, lim, riem,                \
                                        recon_prim != 0, imex != 0, dt, nsub);                      \
  }                                                                                                 \
  extern "C" void adc_compiled_advance_p(double* U, const double* aux, int n, double dx, double dy, \
                                         int periodic, const char* lim, const char* riem,           \
                                         int recon_prim, int imex, double dt, int nsub,             \
                                         const double* pvals, int npar, double pos_floor) {         \
    adc::compiled_block::advance<MODEL>(U, aux, n, dx, dy, periodic != 0, lim, riem,                \
                                        recon_prim != 0, imex != 0, dt, nsub, pvals, npar,          \
                                        pos_floor);                                                 \
  }                                                                                                 \
  extern "C" double adc_compiled_max_speed(const double* U, const double* aux, int n, double dx,    \
                                           double dy, int periodic) {                               \
    return adc::compiled_block::max_speed<MODEL>(U, aux, n, dx, dy, periodic != 0);                 \
  }                                                                                                 \
  extern "C" double adc_compiled_max_speed_p(const double* U, const double* aux, int n, double dx,  \
                                             double dy, int periodic, const double* pvals,          \
                                             int npar) {                                            \
    return adc::compiled_block::max_speed<MODEL>(U, aux, n, dx, dy, periodic != 0, pvals, npar);    \
  }                                                                                                 \
  extern "C" void adc_compiled_poisson_rhs(const double* U, double* rhs, int n) {                   \
    adc::compiled_block::poisson_rhs<MODEL>(U, rhs, n);                                             \
  }                                                                                                 \
  extern "C" void adc_compiled_poisson_rhs_p(const double* U, double* rhs, int n,                   \
                                             const double* pvals, int npar) {                       \
    adc::compiled_block::poisson_rhs<MODEL>(U, rhs, n, pvals, npar);                                \
  }                                                                                                 \
  extern "C" void adc_compiled_to_conservative(const double* P, double* U, int n) {                 \
    adc::compiled_block::to_conservative<MODEL>(P, U, n);                                           \
  }                                                                                                 \
  extern "C" void adc_compiled_to_conservative_p(const double* P, double* U, int n,                 \
                                                 const double* pvals, int npar) {                   \
    adc::compiled_block::to_conservative<MODEL>(P, U, n, pvals, npar);                              \
  }                                                                                                 \
  extern "C" void adc_compiled_to_primitive(const double* U, double* P, int n) {                    \
    adc::compiled_block::to_primitive<MODEL>(U, P, n);                                              \
  }                                                                                                 \
  extern "C" void adc_compiled_to_primitive_p(const double* U, double* P, int n,                    \
                                              const double* pvals, int npar) {                      \
    adc::compiled_block::to_primitive<MODEL>(U, P, n, pvals, npar);                                 \
  }
