#pragma once

#include <adc/core/model/physical_model.hpp>  // aux_comps<M>: aux width of the wrapped model
#include <adc/core/state/state.hpp>
#include <adc/core/foundation/types.hpp>

#include <memory>

/// @file
/// @brief TYPE-ERASED model interface: runtime dispatch of a model (via vtable).
///
/// The production solver is TEMPLATE: `CompositeModel<Hyperbolic, Source, Elliptic>` is known at
/// compile time, which allows inlining and GPU execution (Kokkos). But a model GENERATED at
/// runtime (a DSL brick compiled to .so then loaded) has no type known at compile time.
/// `IModel<NV>` provides the bridge: a virtual interface (flux + max_wave_speed) that any
/// static model satisfies via `ModelAdapter`.
///
/// HOST / PROTOTYPING path only: virtual calls do NOT go into a GPU kernel and cost an indirect
/// jump per cell. This is the COMPILED counterpart of `adc.PythonFlux` (one notch faster, without
/// the GIL). GPU/MPI production stays on the template path. Do not use in the hot loop of
/// high-performance cases.

namespace adc {

/// Hyperbolic model seen behind a virtual interface (runtime dispatch).
template <int NV>
struct IModel {
  using State = StateVec<NV>;
  static constexpr int n_vars = NV;

  virtual ~IModel() = default;
  virtual State flux(const State& u, const Aux& a, int dir) const = 0;
  virtual Real max_wave_speed(const State& u, const Aux& a, int dir) const = 0;
  /// Source term S(U, aux) (default: zero, model without source).
  virtual State source(const State&, const Aux&) const { return State{}; }
  /// Elliptic right-hand side f(U) of the system Poisson (default: zero, no coupling).
  virtual Real elliptic_rhs(const State&) const { return Real(0); }
  /// Conservative -> primitive conversion (P = M.to_primitive(U)). The DSL/CompositeModel exposes it
  /// (hyperbolic brick); a model without conversion (pure scalar) leaves it as the IDENTITY
  /// (prim == cons), which is exact for scalar transport. Used by host marshaling of
  /// System::get_primitive_state. Prim shares the same NV width as State (cf. concept).
  virtual State to_primitive(const State& u) const { return u; }
  /// Primitive -> conservative conversion (U = M.to_conservative(P)). Counterpart of to_primitive;
  /// used by System::set_primitive_state (init from primitives). Identity by default.
  virtual State to_conservative(const State& p) const { return p; }
  /// Width of the aux channel that the model READS (cf. aux_comps). Lets the System runtime
  /// size and marshal the right number of components to the host path (B_z...).
  /// Default: base contract (phi/grad), for a model that does not read any extra field.
  virtual int n_aux() const { return kAuxBaseComps; }
};

/// Adapts a STATIC model M into IModel<M::n_vars>. M may be a hyperbolic brick (flux +
/// max_wave_speed) or a full CompositeModel (flux + source + elliptic_rhs): source / elliptic_rhs
/// are forwarded WHEN M exposes them (otherwise default value). Lets a model GENERATED by the DSL
/// (CompositeModel<GenHyp, GenSrc, GenEll>) be loaded at runtime as a real coupled block.
template <class M>
struct ModelAdapter final : IModel<M::n_vars> {
  using State = StateVec<M::n_vars>;
  M model{};

  ModelAdapter() = default;
  explicit ModelAdapter(M m) : model(m) {}

  State flux(const State& u, const Aux& a, int dir) const override { return model.flux(u, a, dir); }
  Real max_wave_speed(const State& u, const Aux& a, int dir) const override {
    return model.max_wave_speed(u, a, dir);
  }
  State source(const State& u, const Aux& a) const override {
    if constexpr (requires(const M& mm, const State& s, const Aux& aa) { mm.source(s, aa); })
      return model.source(u, a);
    else
      return State{};
  }
  Real elliptic_rhs(const State& u) const override {
    if constexpr (requires(const M& mm, const State& s) { mm.elliptic_rhs(s); })
      return model.elliptic_rhs(u);
    else
      return Real(0);
  }
  // Conversions cons <-> prim forwarded WHEN M exposes them (hyperbolic brick: to_primitive /
  // to_conservative). M::Prim shares the NV width of State (HyperbolicPhysicalModel contract), so
  // the return aligns directly on State. Model without conversion (scalar) -> identity (default),
  // exact for scalar transport (prim == cons).
  State to_primitive(const State& u) const override {
    if constexpr (requires(const M& mm, const State& s) { mm.to_primitive(s); })
      return model.to_primitive(u);
    else
      return u;
  }
  State to_conservative(const State& p) const override {
    if constexpr (requires(const M& mm, const State& s) { mm.to_conservative(s); })
      return model.to_conservative(p);
    else
      return p;
  }
  int n_aux() const override { return aux_comps<M>(); }  // e.g. 4 if a brick reads B_z
};

/// Factory: wraps a static model in an owned IModel (unique_ptr).
template <class M>
std::unique_ptr<IModel<M::n_vars>> make_dynamic(M model = {}) {
  return std::make_unique<ModelAdapter<M>>(model);
}

}  // namespace adc
