#pragma once

#include <adc/core/physical_model.hpp>  // aux_comps<Model>: aux width requested by the model
#include <adc/runtime/block_builder.hpp>
#include <adc/runtime/system.hpp>

#include <functional>
#include <string>
#include <utility>

/// @file
/// @brief add_compiled_model: wires a COMPILED model (a CompositeModel, typically generated by
///        the DSL then included at COMPILE time) as a NATIVE block of the System.
///
/// Difference with System::add_compiled_block (.so + extern "C" ABI + flat-array marshaling, for
/// RUNTIME prototyping on the Python side): here the model is known at compile time, so
/// block_builder builds the closures on the System's REAL GRID CONTEXT (grid_context) and the block
/// runs EXACTLY the production path -- the residual does fill_boundary (MPI halos) + assemble_rhs
/// (Kokkos) on the System's real MultiFab, WITHOUT any copy: the SAME make_block as add_block.
/// Parity validated on CPU (build/ AND Kokkos Serial backend): eval_rhs bit-identical to add_block
/// (see tests/test_compiled_model_parity.cpp).
///
/// DEVICE (Kokkos Cuda backend): the make_block TRANSPORT path is built on NAMED FUNCTORS
/// (build_block via AdvanceExplicit/AdvanceImex/RhsInto/BlockRhsEval, make_max_speed via MaxSpeed;
/// see block_builder.hpp), instead of lambdas first-instantiated from this calling TU. nvcc then
/// reliably emits the nested device kernel (AssembleRhsKernel): the A==B parity (dres=0) of the
/// transport residual is obtained on a CUDA device. This is the "compiled" backend of the ideal
/// m.compile_or_jit() for a production binary.
///
/// THE SAME limit held for the ELLIPTIC / MESH path of solve_fields (fill_boundary, physical BC,
/// Poisson operator, GS smoother, MultiFab arithmetic), kept as inline extended lambdas and thus
/// victims of the SAME nvcc bug: Release Cuda WITHOUT -g segfaults in solve_fields (Heisenbug:
/// OK Serial + compute-sanitizer + -g). These kernels are likewise converted to named
/// functors (mf_arith / fill_boundary / physical_bc / poisson_operator / geometric_mg). The CUDA
/// parity of the FULL PRODUCTION path (solve_fields + transport, np=1) is validated once the
/// solve_fields segfault above is closed; the MPI multi-rank cases of the non-split System remain a
/// separate follow-up. Device-codegen provenance: docs/validation/HEADER_PROVENANCE.md.

namespace adc {

/// Adds @p model (CompositeModel) as a native block of @p sys with the requested scheme (limiter x
/// riemann, reconstruction, time treatment). @p gamma is used by set_density (rest energy, 4 vars).
///
/// @code{.cpp}
/// adc::System sys(cfg);
/// // model: an adc::dsl model compiled into a CompositeModel at build time (the production seam;
/// // runs the exact add_block path on the System's real grid, no copy).
/// adc::add_compiled_model(sys, "flow", model, "minmod", "hll", "conservative", "explicit");
/// sys.set_poisson("charge_density", "geometric_mg");
/// sys.step_cfl(0.4);
/// @endcode
template <class Model>
void add_compiled_model(System& sys, const std::string& name, Model model,
                        const std::string& limiter = "minmod",
                        const std::string& riemann = "rusanov",
                        const std::string& recon = "conservative",
                        const std::string& time = "explicit", double gamma = 1.4,
                        int substeps = 1, bool evolve = true, int stride = 1,
                        double positivity_floor = 0) {
  const bool imex = (time == "imex");
  const bool recon_prim = (recon == "primitive");
  // EXPLICIT RK scheme marshaled by the production path (add_native_block -> adc_install_native
  // -> this template): "ssprk3" (3 stages, order 3, less dissipative, to pair with weno5), "euler"
  // (ForwardEuler, order 1: fidelity to first-order references, validation) vs "ssprk2"
  // (historical default, bit-identical). Has effect ONLY on the explicit advance -- IMEX keeps its
  // ForwardEuler half-step + implicit source, so method is ignored when imex. We thus align the
  // production .so with the native add_block path (system.cpp) which already exposed ssprk3; any
  // other string ("explicit"/unknown) falls back to ssprk2 (add_native_block validates the upstream string).
  const std::string method = (time == "ssprk3") ? "ssprk3"
                             : (time == "euler") ? "euler"
                                                 : "ssprk2";
  // The block may read extra auxiliary fields (aux_comps<Model> > 3, e.g. B_z of a magnetized
  // source): we widen the System's SHARED aux channel BEFORE capturing its address, so that the
  // closure reads a wide enough aux. Base model (3) -> no-op, unchanged.
  sys.ensure_aux_width(aux_comps<Model>());
  const GridContext ctx = sys.grid_context();
  BlockClosures clo = make_block(model, limiter, riemann, ctx, imex, recon_prim, method, {}, {},
                                 nullptr, static_cast<Real>(positivity_floor));
  std::function<Real(const MultiFab&)> ms = make_max_speed(model, ctx);
  std::function<void(const MultiFab&, MultiFab&)> pr = make_poisson_rhs(model);
  sys.install_block(name, Model::n_vars, Model::conservative_vars(), Model::primitive_vars(),
                    gamma, std::move(clo), std::move(ms), std::move(pr), substeps, evolve, stride);
  // cons <-> prim conversions OF THE MODEL (set/get_primitive_state): same formulas as the flux of
  // the production path. Set AFTER install_block (like set_block_ghosts); a native .so loader
  // recompiled against this header (ABI key verified) carries them too.
  auto conv = make_cell_convert(model);
  sys.set_block_conversion(name, std::move(conv.first), std::move(conv.second));
  // OPTIONAL step bounds of the model (HasSourceFrequency / HasStabilityDt traits, see
  // core/physical_model.hpp): compiled here like flux/source (a DSL model declaring
  // m.source_frequency(...) / m.stability_dt(...) carries them down to the System's step_cfl).
  // EMPTY functions if the model does not declare the traits -> historical step policy. The
  // STABILITY speed (HasStabilitySpeed) is already carried by make_max_speed above.
  sys.set_block_dt_bounds(name, make_source_frequency(model, ctx), make_stability_dt(model, ctx));
  // Scheme GHOSTS: WENO5 reads a 5-point stencil (3 ghosts) > the 2 allocated by install_block.
  // We reallocate the block state with block_n_ghost(limiter) -- SAME mechanism as add_block (PR #88) --
  // so that fill_boundary + assemble_rhs do not read out of bounds on the System's real MultiFab.
  // none/minmod/vanleer (<= 2 ghosts): no-op, allocation and result bit-identical to before.
  sys.set_block_ghosts(name, block_n_ghost(limiter));
}

}  // namespace adc
